#!/bin/bash

# path modifiers
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/bin"
export PATH="$(go env GOPATH)/bin:$PATH"

# homebrew versions of python install scripts
# in /Users/$USER/Library/Python/*/bin
for pdir in /Users/$USER/Library/Python/*/bin; do
    export PATH="$pdir:$PATH"
done

# brew install ruby
if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
  export PATH="$(gem environment gemdir)/bin:$PATH"
fi