homebrew_installed_packages:
  - cowsay
  - dust
  - fd
  - github/gh/gh
  - go
  - libgit2
  - openjdk
  - openssl
  - postgresql
  - procs
  - python@3.10
  - shellcheck
  - starship
  - thefuck
  - tree
  - zoxide

cargo_packages:
  - bat
  - exa